import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { ModalProvider } from "@/components/modal/modalProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <ModalProvider>{children}</ModalProvider>
        </Provider>
      </body>
    </html>
  );
}
